### ISSUE TITLE
Add SvgChart and Axes to the public interface

### ISSUE THREAD

**Issue by martinfrances107** [theta-vn/leptos_chart#11]
I really like the project .. I am finding it useful in several project 

I would like to have a conversation about using this library from a developers point of view.

If I want to use the "Axes" feature in isolation (without the other features like "LineChart" then I get a compilation errors because core is not available.  ) 

To make this library more generic this is a simple fix.
-Axes = []
+Axes = ["core"]

Also to make this library more generic... I  want to expose the SvgChart component. 

Inside my module  I want to import SvgChart and create child objects  to reflect my custom code.

I have a PR which I think makes the minimum change 
There are many was to achieve this goal..  so I created this issue as well as the PR so we can discuss the best way forward.

One thing I think is missing from the minimum change .. is a example which shows a custom chart.
But I think the discussion here may change the solution.

**Comment by martinfrances107** [comment]
I have now added a "example/custom_chart" to the PR to  show the what I want to acheive.

**Comment by LangPham** [comment]
I'll close this. It is not issue! It is new feature.
