### ISSUE TITLE
use of undeclared crate or module `tracing`

### ISSUE THREAD

**Issue by cb-systems** [theta-vn/leptos_chart#14]
Compiling leptos_chart v0.2.2
error[E0433]: failed to resolve: use of undeclared crate or module `tracing
for:
--> C:\...\leptos_chart-0.2.2\src\axes\xaxis.rs:7:1
--> C:\...\leptos_chart-0.2.2\src\axes\yaxis.rs:7:1
-->C:\...\leptos_chart-0.2.2\src\linechart\components.rs:62:1

#[component]
   | ^^^^^^^^^^^^ use of undeclared crate or module `tracing`
   |
   = note: this error originates in the attribute macro `::leptos::leptos_dom::tracing::instrument` (in Nightly builds, run with -Z macro-backtrace for more info)

I tried adding tracing to my leptos app Cargo.toml, but it still won't compile leptos_chart - any suggestions?

**Comment by LangPham** [comment]
I updated version leptos to 0.6, can you check again!
