### ISSUE TITLE
Resolve security advisory

### ISSUE THREAD

**Issue by martinfrances107** [theta-vn/leptos_chart#4]
I love this project .. I am trying to get a long chain of security advisory warnings resolved from a project I am working on 

When I run ```cargo audit``` on this project I get this warning 

```
Crate:     time
Version:   0.1.45
Title:     Potential segfault in the time crate
Date:      2020-11-18
ID:        RUSTSEC-2020-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2020-0071
Severity:  6.2 (medium)
Solution:  Upgrade to >=0.2.23
Dependency tree:
time 0.1.45
└── chrono 0.4.26
    └── theta-chart 0.0.5
        └── leptos_chart 0.1.0
```

I have created these issues  in [theta-chart](https://github.com/theta-vn/theta-chart/issues/1) and [chrono](https://github.com/chronotope/chrono/issues/1223)

When those are complete the fix here will be simple.

**Comment by LangPham** [comment]
Thanks you,
- Temporarily update to version 0.1.2 while waiting for chrono to fix.
